### ISSUE TITLE
如何获取API文档？

### ISSUE THREAD

**Issue by feilongproject** [tencent-connect/bot-docs#140]
我想使用typescript开发机器人，但是在`docs/develop`下无法找到相关文档，且其他文档中关于基础API的链接均已失效，目前在历史提交中只能找到`ec49252`这次关于基础API最后一次提交（下一次提交已移除api目录）。请问如何获取最新的api文档？

**Comment by jackqqxu** [comment]
https://bot.q.qq.com/wiki/develop/api/
可以参考这里
