### ISSUE TITLE
请问有java sdk的文档吗

### ISSUE THREAD

**Issue by chrelyonly** [tencent-connect/bot-docs#143]
请问有java sdk的文档吗

**Comment by jackqqxu** [comment]
对不起，目前暂无 java 文档；
SDK
golang: [https://github.com/tencent-connect/botgo(opens new window)](https://github.com/tencent-connect/botgo)
nodejs: [https://github.com/tencent-connect/bot-node-sdk(opens new window)](https://github.com/tencent-connect/bot-node-sdk)
python: https://github.com/tencent-connect/botpy

https://bot.q.qq.com/wiki/develop/api/#%E6%8E%A5%E5%8F%A3%E8%AF%B4%E6%98%8E 可以参考这里
