### ISSUE TITLE
证书过期

### ISSUE THREAD

**Issue by FoskyM** [tencent-connect/bot-docs#144]
![W{{%PZPUDQA}41K3U0L~43N](https://user-images.githubusercontent.com/39661663/183230808-e7e16c6d-7781-4311-abdd-bde8244a5555.png)
![R6S(X~TGU0%0)3T94T}XR%E](https://user-images.githubusercontent.com/39661663/183230815-8f991997-43ac-402f-b085-319eaafcd453.png)

cdn的证书貌似过期了，无法正常打开文档，显示不安全

**Comment by wzpan** [comment]
昨日已经修复，感谢反馈
