### ISSUE TITLE
API获取调用凭证报错[bug?]

### ISSUE THREAD

**Issue by yxjsxl** [tencent-connect/bot-docs#220]
API获取调用凭证报错:internal err
完整返回的是{'code': 100002, 'message': 'internal err'}
编程环境:python
data={
        'appId':'正确的',
        'clientSecret':'正确的'
}
hd={'Content-Type':'application/json'}
ATK_now = requests.post(url="https://bots.qq.com/app/getAppAccessToken",data=data,headers=hd)

**Comment by aJarOfCode** [comment]
我也遇到同样的错误，问题似乎并不出在本地。似乎每次请求都会向https://bots.qq.com/app/getAppAccessToken获取access_token，如果请求超时，捕获asyncio.TimeoutError异常，并打印超时信息。如果响应数据中没有access_token或expires_in字段，打印错误信息并抛出RuntimeError异常。显然我们遇到了第二种情况。当成功之后才会返回机器人的token。我目前还没找出解决办法。

**Comment by yxjsxl** [comment]
这个iss打开时间是24Jul22，现在已经24Dec22，处理速度有点过于慢了吧

**Comment by yxjsxl** [comment]
问题解决，data的数据需要json.dumps()一下，而且appid需要str下
